### ISSUE TITLE
Add docs on usage of various fields in the test spec

### ISSUE THREAD

**Issue by princerachit** [gitpod-io/dazzle#39]
<del>Add docs on usage of `entrypoint` field in tests and when to use it and when not to use it</del>

Add docs on usage of various fields in [the test spec](https://github.com/gitpod-io/dazzle/blob/bf842818b9df2c5209fc2e0cab9981cc4a04ff5f/pkg/test/test.go#L26-L34)

**Comment by kylos101** [comment]
Hey Prince, there are a [couple other items from the Spec](https://github.com/gitpod-io/dazzle/blob/bf842818b9df2c5209fc2e0cab9981cc4a04ff5f/pkg/test/test.go#L26-L34) that are worth showing in the examples..
